### ISSUE TITLE
continuous refresh

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#10]
@targos 

The hooks and story board has been implement by @hamed-musallam but currently as you can see on https://cheminfo.github.io/nmr-displayer/ using the react developper tools there is a continuous refresh.

Is there a way to know what triggers the refresh ?

Is it normal that the onEffect in the code :
https://github.com/cheminfo/nmr-displayer/blob/7485ce761380dc8b10f23b926078bd62123839c0/src/component/axis-y.jsx#L27
has no second arguments ?

**Comment by hamed-musallam** [comment]
I think the problem because i didn't add [] as a second parameter to the useEffect hock so it will trigger once after the component is rendered, it's like componentDidMount lifecycle.

**Comment by targos** [comment]
A few comments on this file:

- since the `axis` and `scale` and `getScale` variables are only used in the `useEffect` hook, they should be created inside it
- `getDomain` doesn't use any local variable. It can be created once outside the function component
- the dependencies array of `useEffect` should include every variable that is used in the effect because if you provide an empty array, a change in the props will not update the axis. In this case, I think it should be `[show, data, height, margin, label, height, onAxisDidMount]`. The development server of create-react-app should print a warning about this in the console.

**Comment by lpatiny** [comment]
@hamed-musallam If a commit fix an open ticket try to use in the commit message `close XXX` where XXX is either the ticket number of the full URL to the ticket. This will automatically add a link in the ticket to the commit and close the ticket.
