### ISSUE TITLE
How pass event's specially mouse over event from one layer to another

### ISSUE THREAD

**Issue by hamed-musallam** [cheminfo/nmr-displayer#105]
@lpatiny @targos  @stropitek 

What we have after the laste refactory that i don't know how to pass events from one to layer to another for example 
```
<div>
<div1></div1>
<div2></div2>
<div>
```
so if we have mouse event on div2 it's the same width and height of the div 1 and i need  to pass the same event to elements in div1 how we can do it ?

**Comment by stropitek** [comment]
Can you give us the context? What are you trying to achieve by doing this?

(http://xyproblem.info/ 😉 )

**Comment by hamed-musallam** [comment]
> Can you give us the context? What are you trying to achieve by doing this?
> 
> (http://xyproblem.info/ 😉 )

After i do some refactory specially for pealNotationTool i seperated the display the notifications itself from the tool and the mouse event on svg element that hold all tool beside the pealnotification tool 
and Display the peaks in other layer beside the LineSeries and IntegralSeries so if my mouse come over the peak nothing happen.

**Comment by stropitek** [comment]
Can you point me to the commit where you did this refactoring?

**Comment by hamed-musallam** [comment]
this the commit point where i make the changes that i told you bout it before
https://github.com/cheminfo/nmr-displayer/commit/e4c1cb65c1f846219a9352450387df1364377e48

**Comment by stropitek** [comment]
Hello @hamed-musallam,

I spent some time thinking about the design of the react components to handle display and interaction in a developper friendly way without limiting the possibilities the tool should allow.

I published an example here: https://codesandbox.io/s/great-architecture-sly9j

Basically I designed it like this
```jsx
<MouseTracker> // provides mouse tracking data in a context
  <BrushTracker> // provides brush tracking data in a context
    <Chart /> // renders the main chart
    <Crosshair /> // renders crosshair based on the mouse tracking context
    <Brush /> // renders brush based on brush tracking context
  </BrushTracker>
</MouseTracker>
```

It allows for a better separation of concerns. Some components are responsible for tracking user events and transforming them into meaningful state that can easily be reused by downstream components who are only responsible of rendering the appropriate graphic.

For example before it would have been difficult for the Crosshair rendering component to know that it should not render because the user is currently making a brush selection.

The tracker components can be reused for different purposes. For example the BrushTracker can be used for X zoom, Y zoom, XY zoom, vertical / horizontal scaling with the mouse, x, y and xy-panning. The only thing changing between those use cases would be the callback that would dispatch different actions to the Chart reducer when the brush selection changes / ends.

Also you can use my example to implement the new optimized brush display. As for Crosshair, It only changes the transform style property to allow for gpu acceleration and ensure the svg is painted by the browser in a different layer to avoid slowness.

I'd like still to discuss this will @lpatiny but we will soon create more concrete issues for you to work on.

**Comment by hamed-musallam** [comment]
@stropitek 
Thank you very much for your time and your effort, i followed what you suggest and i refactoring the code according to that, Can you check the code at 
[https://github.com/cheminfo/nmr-displayer/commits/refactor-tool
](url)
and after that i have problem i need to discuss it with you.

**Comment by stropitek** [comment]
The problem is not the component. If you use the react profiling tool you will see that no components are taking time to render. The problem is that each time we re-render the crosshair, the browser is also repainting the complex svg (on every mouse move!). You can see that if you make a recording of the performance in chrome dev tools. The bottle neck is "rasterizing", which is the rendering of the svg. I don't know how to solve it, I've already tried to use the will-change css property which is supposed to force the browser to create rendering layers.

**Comment by stropitek** [comment]
The issue seems to be in Chrome. Rendering performance is much better in Firefox and Safari.

**Comment by stropitek** [comment]
I've found the culprit! I have no idea of why, but when removing the `display: grid` of the `ToggleButtonGroup`  component (a child of the `Toolbar` component) from material-ui, the performance is restored in Chrome.

I discussed it with my colleagues and our recommendation is not to use a UI library within the core of the spectra displayer. It's fine to use it within the application shell but using it in the spectra displayer forces us to use this library if we want to include it in another project.

Even if it is a quiet big undertaking, I would suggest that you refactor everything within `<NmrDisplayer />` to not use the material ui library. It's fine to use libraries for layout like the Split Pane. In order for the nmr displayer to be usable as a library, we should not put the css rules in css files as the consumer of the library would have to include them manually. Instead we recommend that you use a css-in-js library. We have used [emotion](https://emotion.sh/docs/introduction) in the past and are happy with it.

**Comment by stropitek** [comment]
@hamed-musallam 

If you want performance to be better on Chrome, you need to re-implement (make your own implementation) of the toggle button group without using `display: grid`. https://github.com/cheminfo/nmr-displayer/blob/deb7463738608190e5f8936b7e9ffa5a7aaf4fa5/src/component/css/spectrum-chart.css#L58

Also can you move css definitions from css files to using the emotion library. If there is css you need to reuse across the library, make reusable components instead of reusable css classes.

**Comment by stropitek** [comment]
Also we noticed that you are commenting a lot of code. You should remove it instead. You can always go back to old code by using git.
