### ISSUE TITLE
Line broadening

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#123]
Does somebody has the algorithm to make the line broadening on the FID ?

**Comment by jliermann** [comment]
As far as I know, you simply multiply the FID to an exponential function:

FID'(t) = FID(t) * exp(-nt)

The user can choose the parameter n in Hz, typically 0.3 Hz for 1H and 1-2 Hz for 13C.

**Comment by jwist** [comment]
Line broadening on the FID is called apodization, it consists in
multiplying the FID with a function, generally exponencial to damp the
spectra.
The most used one is just an exponential, but sine, or sine^2 cos, cos² can
also be used.

Director de la Oficina de Transferencia
de Resultados de Investigación -OTRI
Dr.Sc. Assistant Professor (Chemistry Department)
Universidad del Valle, Cali, Colombia
website: http://www.cheminfo.org


*AVISO LEGAL:* Este mensaje y/o sus anexos son confidenciales y para uso
exclusivo de su destinatario intencional. Si usted no es el destinatario,
le informamos que no podrá usar, retener, imprimir, copiar, distribuir o
hacer público su contenido. Cualquier retención, revisión no autorizada,
distribución, divulgación, reenvío, copia, impresión, reproducción o uso
indebido de este mensaje y/o anexos, está estrictamente prohibida y
sancionada de acuerdo con la Ley 1273 de enero del 2009. Si ha recibido
este correo por error, por favor elimínelo e infórmenos al correo
xxxxxx@correounivalle.edu.co Si usted es el destinatario, le solicitamos
mantener reserva sobre el contenido, los datos o información de contacto
del remitente y en general sobre la información de este documento y/o
archivos adjuntos, a no ser que exista una autorización explícita.

**Comment by djeanner** [comment]
This answer is trivial - I hope that is answeriung the question!
Concerning the algorithm:
**Answer 1):** According to what I have seen in some code, the fastest way to produce an exponential multiplication is to work with double precision floating points, have a coefficient (c) initially set to 1, determine a factor of reduction (f, set according to the LB, or whatever unit used ) for the product and then in the loop running through the array of the points of the FID, 
c=1;
f=...;// typilcally 0.99...
// if the first point of the fid is not recorded for time zero, one should shift by the correct time...
// in 2D spectra, the first time increment is ofter 0.5*dw or 1*dw. In this case, c has to be adjusted.
for (i=0;n<nb;i++){
fid(i)=fid(i)*c;
c=c*f;
} . f and c should be in double precision because of the error propagation. I guess that the array of the spectrum can be a float. But this approach is not very readable (because the property of the function is implicit - and not generally applicable.
**Answer 2):** I would rather programm the apodization in a more readable and modular manner where you fill a window_function array and then apply the multiplication.
//for line broadening exp(nt)
// generation
for (i=0;i<n;i++) window_fn(i)=exp(i*n);
// 
for (i=0;i<n;i++) fid(i)=fid(i)*window_fn(i);
The loop to apply the window function would scan through two separate arrays which may be not as fast, but I don't think we are limited here (see my early comment about the fact that we should rather interpolate after F(F)T rather than use wild zerro filling before FT. It does not require double precision.
If you make a starting function, I can take care of the different window function. Just know that in order to generare the array, one need to know the number of points, but also the time corresponding to the last point of the FID (t1, max)- so the latter should be send as parameter to the window_function generator. (not all window function need it, but some do).

If you make a starting window_function generator with the exponential in it, I can take care of adding other window functions in it.

**Comment by nes-cgn** [comment]
It would make sense to have an option (somewhere) to change from the default apodization function from exponential to something else. Mainly, once the 2D experiments are treated this will be important. Also, it would be good if one could see somewhere which window function is used.

**Comment by lpatiny** [comment]
Basic apodization has been implemented
