### ISSUE TITLE
baseline correction

### ISSUE THREAD

**Issue by nes-cgn** [cheminfo/nmr-displayer#194]
For integration etc. it would be useful

**Comment by lpatiny** [comment]
@hamed-musallam Please prepare a button that allows to select zones in the spectrum and call a method sending this array of {from:, to:}. @jobo322 will prepare the code for manual baseline correction.

@jobo322 will also prepare the code for automatic baseline correction.

Because there may be many different algorithm for baseline correction I'm thinking that one button will change the header and the header may have a select drop down menu with currently the following options:
* manual
* airPLS
If manual is selected we should define zones in the spectrum. If airPLS is selected you will be able to enter some parameters (to check with @jobo322)

**Comment by hamed-musallam** [comment]
@jobo322 
Can you complete this feature.

**Comment by jobo322** [comment]
Hello @lpatiny,
 what do you mean with manual baseline correction

**Comment by lpatiny** [comment]
Actually it was manual selection of the different zones that corresponds to the noise. I think this is what you implemented no ?

**Comment by jobo322** [comment]
At the moment those zones are used for baseline correction by airpls algorithm, In this way we force to fit those zones to improve the baseline correction. This is a semi-automatic way. 

I think after select some zones we always need a optimization step to adjust the global baseline of spectrum.

**Comment by jobo322** [comment]
May be we will support several baseline correction algorithm,  so we should to have a list of algorithms supported and change the top bar depending of selected algorithm. At the moment we have the airpls algorithm ready to use on nmr-displayer The airpls algorithm require 3 parameters

`{ 
name: lambda, 
minValue: 1, 
maxValue: 10^9, 
defaultValue: 500 
}`

`{ name: factorCriterion, minValue: 0, maxValue: 1, defaultValue: 0.003 }`

`{ name: maxIterations, minValue: 1, maxValue: 1000, defaultValue: 50}`

If λ (lambda) is too large, the fitted baseline will be too flat. If λ is too small, the fitted baseline will be too flexible to include the peak parts. So, λ should change in big steps, and λ grid should be linear for log(λ)

**Comment by jobo322** [comment]
There is another method ready to import in nmr-displayer, there is a regression based baseline correction. This method accepts any kind of regression with it's respective options (depends of baseline shape). By default it's working with polynomial regression.
`{
    Regression = PolynomialRegression, // we could to fit several forms of baseline curves (sin, polynomials) it should to select from a drop down menu
    regressionOptions, // depends of selected function those options should appear to modify it.
    maxIterations = 100, // general for each method
    tolerance = 0.001, // general for each method
    reduce = true, // general for each method
    nbPoints = 4001 // general for each method
  }`

we should select which function we want to support, for polynomial regression we need the polynomial's degree
