### ISSUE TITLE
export option for reporting/printing

### ISSUE THREAD

**Issue by nes-cgn** [cheminfo/nmr-displayer#218]
For use in a lab class, it would be useful if there was any kind of pdf creator and/or copy-paste screen option or a way to print the processed spectrum

**Comment by lpatiny** [comment]
@hamed-musallam Please add an export button that allows to export as SVG. SVG being a vectorial format it will be high quality.

This button will simply take the content of the SVG element and save it.

There may be some other libraries to save the file. I used up to now: https://www.npmjs.com/package/file-saver

**Comment by lpatiny** [comment]
This download icon could be placed next to the full screen icon.

**Comment by hamed-musallam** [comment]
@lpatiny 
this feature we need to discuss about, because any element not belong to basic svg elements will produce an error, And Also at some point specially in ranges and peaks and  integrals i have svg buttons to delete each one it and it will exported with svg we need to delete all these elements.

**Comment by lpatiny** [comment]
Indeed all the 'foreignObject' objects should be removed before SVG exportation. Do you see a simple way to achieve this ?

**Comment by hamed-musallam** [comment]
it's done

**Comment by lpatiny** [comment]
I just discussed with @targos that suggest a simpler method

The goal would be to add a property in the elements that should not be exported: `data-no-export="true"`  (all the properties starting with 'data-' are custom user properties https://developer.mozilla.org/en-US/docs/Learn/HTML/Howto/Use_data_attributes).

After the SVG being in the dom you can use something like:
```js
var clone = svg.cloneNode(true)
var toRemove = clone.querySelectorAll('[data-no-export="true"]')
toRemove.forEach((element) => element.remove())
var svgString = svg.outerHTML
```

**Comment by targos** [comment]
I'm pretty sure it doesn't work properly in MS Word because the SVG doesn't have a specified size (width and height are missing on the <svg> tag)

**Comment by lpatiny** [comment]
Indeed adding width and height helps. I can import without problem in word 2016 on osx. Based on wikipedia SVG support is standard in office 2019 so I guess the students should update their software if they use old version of word.

Otherwise they should make a screen capture but they will have a lower resolution obviously. Maybe we could convert it to png using https://www.npmjs.com/package/canvg but again it will be pixels.

![image](https://user-images.githubusercontent.com/1484241/70820200-63a32880-1dd8-11ea-8675-951be7cdb680.png)

**Comment by lpatiny** [comment]
It seems that we have have a png we could copy it to the clipboard: https://web.dev/image-support-for-async-clipboard/

**Comment by hamed-musallam** [comment]
it's Implemented, you can  export the experiments as SVG, PNG , and also copy to clipborad

**Comment by nes-cgn** [comment]
For some reasons, the copy to clipboard funtion does not work any longer. Also, if exporting an .svg file, this looks very strange when imported in MS word (it becomes black, see screenshot). Export as .nmrium and as .png do work flawlessly. However, at least the copy/paste would be important for the upcoming lab class (reports)
![svg_COSY](https://user-images.githubusercontent.com/47237343/95891380-4c7cf080-0d85-11eb-952f-d4cfc56c4323.PNG)

**Comment by hamed-musallam** [comment]
@lpatiny 
the ClipboardItem not supported at Firefox this why we can not copy to clipboard. do you have any suggestion?

@nes-cgn 
i tested it on Firefox version 81 and you can save it as png or svg and import it with out any problem, what the version of Firefox that you use?  can you update your Firefox to last release and test again but you still can not copy and past from Firefox but in Google Chrome all the export feature work well
