### ISSUE TITLE
move the "zoom out" button just below the "zoom" icon

### ISSUE THREAD

**Issue by djeanner** [cheminfo/nmr-displayer#267]
![Screenshot 2020-01-10 10 50 24](https://user-images.githubusercontent.com/26463431/72143530-24e09e00-3397-11ea-9806-b94809d920f9.png)

**Comment by lpatiny** [comment]
@hamed-musallam you should rethink the icon grouping I think because currently the icons don't always have the same distance between them and they don't behave as radio button anymore. You can have many icons selected at the same time

![image](https://user-images.githubusercontent.com/1484241/72235248-62307000-35d1-11ea-97da-0e226e5414cb.png)

**Comment by hamed-musallam** [comment]
it's done.
