### ISSUE TITLE
Bug: Firefox crashes when making .svg from a spectrum

### ISSUE THREAD

**Issue by djeanner** [cheminfo/nmr-displayer#330]
![Screenshot 2020-02-07 17 26 57](https://user-images.githubusercontent.com/26463431/74046651-38e7e180-49cf-11ea-9f30-9255ba14ecb1.png)

**Comment by lpatiny** [comment]
@hamed-musallam Please check that ClipboardItem exists on the browser and show a message 'Your browser does not support this feature, please use Google Chorme' if not available.

Strange on Firefox it is behind flags since version 63 (we are at 72) but even activating those flags does not work. https://developer.mozilla.org/en-US/docs/Web/API/Clipboard

**Comment by hamed-musallam** [comment]
@lpatiny 
i tested this feature at the latest firefox version and there are no problems, but yes we have to show a message if the browser does not support this feature.
