### ISSUE TITLE
Problems with phasing

### ISSUE THREAD

**Issue by evaziegler** [cheminfo/nmr-displayer#352]
[o-toluidin_95-53-4_13c.zip](https://github.com/cheminfo/nmr-displayer/files/4261427/o-toluidin_95-53-4_13c.zip)

I wanted to analyse the attached spectra. If I chlick "phase correction" (1H), the program shows me the message "something went wrong". If I click on details, I can read:

TypeError: F[e] is undefined

    in uo
    in g
    in ForwardRef
    in po
    in svg
    in ForwardRef
    in div
    in Ai
    in div
    in Ni
    in $o
    in div
    in t
    in div
    in t
    in div
    in ForwardRef
    in Kt
    in div
    in div
    in ForwardRef
    in s
    in x
    in Sn
    in t
    in nc
    in div
    in l
    in t
    in t
    in Suspense
    in div
    in div
    in t
    in _
    in t
    in t
    in t
    in t

**Comment by nes-cgn** [comment]
There are more phasing problems - if one imports the Bruker fid files in jcamp format, it is very difficult to do a phase correction. Kirk Marat's suggestion is that this is due to the delay resulting from the digital filter when acquiring the FID. SpinWorks can handle this, and Kirk offered to help us. Attached are the screenshots of the same FID treated by our displayer and SpinWorks
![phasing_060320](https://user-images.githubusercontent.com/47237343/76068896-483c5980-5f92-11ea-9b6a-5c3beb6dd288.PNG)
![phasing_060320_ii](https://user-images.githubusercontent.com/47237343/76068898-4a061d00-5f92-11ea-9a52-378a091acde0.PNG)
![phasing_FID_SpinWorks4](https://user-images.githubusercontent.com/47237343/76068899-4a9eb380-5f92-11ea-8574-d4a062ae2a11.PNG)
![phasing_FID_SpinWorks4_ii](https://user-images.githubusercontent.com/47237343/76068901-4b374a00-5f92-11ea-8e20-8c5391a251ab.PNG)
![phasing_FID_SpinWorks4_iii](https://user-images.githubusercontent.com/47237343/76068902-4bcfe080-5f92-11ea-90e0-233f82be1870.PNG)

**Comment by jwist** [comment]
The implementation was not correct in our code. It is now solved for recent data with digital filter.
