### ISSUE TITLE
If change of kind the highlight is permanent

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#458]
If you change the kind in range (or integral) the highlight of the line becomes permanent

![image](https://user-images.githubusercontent.com/1484241/81281789-96391080-905a-11ea-811d-2bdb847c6056.png)

**Comment by michaelwenk** [comment]
@lpatiny  @hamed-musallam  This is actually what we have seen also in the last meeting on Tuesday.
Sometimes that appears like that, not always. If one clicks on another range and change it then this misbehaviour might not happen.

Either is has to do with the row id and highlighting or with leaving the row field itself when selecting a kind in the list component and the highlighting keeps still on (permanently) because we did not leave the row correctly.

I don’t know. We have to figure it out.
