### ISSUE TITLE
Delete all spectra

### ISSUE THREAD

**Issue by evaziegler** [cheminfo/nmr-displayer#544]
Hello,

at the moment it is not possible to delete all spectra.
![grafik](https://user-images.githubusercontent.com/60426010/88056024-2d910880-cb60-11ea-93e2-760b4681aab4.png)

Kind regards,
Eva

**Comment by evaziegler** [comment]
I wanted to record a new gif. I´ve noticed that it is not possible to delete the 1H spectrum if you´ve opened it after the 13C. I saw "error"

**Comment by hamed-musallam** [comment]
@evaziegler 
Actually what we have right now we can delete all spectrums per tab once not any spectrum select inside that tab.

**Comment by nes-cgn** [comment]
This bug is still existing: If one imports a spectrum and then selects in the "spectra" submenu the "trash can" icon to "delete all spectra", the screen becomes grey and only a reload can re-establish the entrance side, but without experiments. Applies to 2D experiments only, however (cosy, hmqc, hmbc...) as far as I can see.
