### ISSUE TITLE
COSY cross peaks in HMBC/HMQC

### ISSUE THREAD

**Issue by nes-cgn** [cheminfo/nmr-displayer#729]
If a COSY was picked with the zones function, after that, the cross peaks are also visible in the HMBC/HMQC visualization
![COSY_in_HMQC](https://user-images.githubusercontent.com/47237343/101260088-8dfa9e00-372d-11eb-9186-37bc7325e128.PNG)

**Comment by hamed-musallam** [comment]
@lpatiny 
I think it's better if we have a toggle button to hide/show the cross lines, if  you agree with me then where do you want to have this button in point of ui

**Comment by lpatiny** [comment]
The problem is not a hide/show cross lines, the problem is that the zones that are placed in the COSY ends up in the HSQC / HMBC as well

![image](https://user-images.githubusercontent.com/1484241/101477725-e8734480-394f-11eb-8027-62096effbc6f.png)

This is not ok. The zones are not saved at the level of the spectrum ?

I added 'full cytisin' example to debug easily this problem.

**Comment by hamed-musallam** [comment]
@lpatiny 
yes, it is saved at the level of the spectrum and I'm sure from that.

**Comment by hamed-musallam** [comment]
@lpatiny 
   {
        "file": "./data/cytisine/2d/full.json", // this file not exists may be you forgot to upload the file.       
      },

I think it's better to meet to check together this problem
