### ISSUE TITLE
Align spectra

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#730]
When there are a lot of spectra it may be interesting to align them. This is based on a range that you draw (from / to value).

After this what you should do:
1. peak picking for each spectrum in the range
2. select the X biggest value in this range
3. shift the spectrum so that the mean of the selected peaks has the correctly chemical shift (add the correct filter to all the spectra)

But this code already exists ! Simply get inspired by https://github.com/cheminfo/spectra-processor/blob/7c39ba9d27fc29052244262f7bcd15f6f4691d75/src/spectrum/getNormalized.js#L62-L66

Practically:

Add an icon in the multiple spectra panel (nmr-reference)

![image](https://user-images.githubusercontent.com/1484241/101276459-529fb400-37ad-11eb-9cdc-6830ccc5ca6c.png)

When you click on the icon have a new dialog box:

1. Need to specify from / to that can be done interactively with the mouse (same as when you edit ranges)
2. Specify the number of peaks that we need to consider (default 1)
3. Need to specify the new chemical shift that should be used for the mean of the selected peaks

In this dialog box we should also plan a list of predefined values. One click on this list will fill the 4 fields.

This list will depend on nucleus !!!!

@hamed-musallam Please plan that this code is in /data and could be reused somewhere else in the code (I'm thinking that even with one spectrum we could have a set reference tool.

@jwist Could you provide us a list of references used in metabolomics ?

**Comment by jwist** [comment]
The most two common references are TSP which is a singlet at 0ppm and that can be use for calibration. This works nicely for URINE because the concentration in protein is low (should be low). This is not the best solution however for PLASMA and SERUM because it is known to bind to protein and thus may be shifted. In this latter case, the doublet of glucose at 5.23 ppm is used instead for alignment. 

In some cases, several experiments are recorded for the same samples. It is possible to use the calibration obtained on one series and apply it to another series. This is important to calibrate experiment where no glucose peak is observable, because it has been filtered out.

@josoriom already made some functions to perform this task so it may be a good idea to start from this. 

This function is really a calibration function and it already exists in nmr-displayer. What I mean is that it apply to each rows and is independent of the other data in the series, i.e., the correction is absolute to a chemical shift, it is not relative to other spectra.

If we want to go metabolomics we may want to add an other categories of functions that apply to a data-matrix (as opposed to rows) as a whole. For example for centering and scaling the series, it is necessary to compute the mean spectra. Finding the skyline (ceiling) or the bottom lines of a dataset are another example, or to correct for dilution. Most are very simple functions, but require the data to be considered as a whole matrix.

**Comment by lpatiny** [comment]
@hamed I prepared the code to use (but I didn't debug it): https://github.com/cheminfo/nmr-displayer/blob/63ac9d3d979e17511eae35c97c9ae3411bdcb148/src/data/data1d/getReferenceShift.js#L16-L28

**Comment by hamed-musallam** [comment]
@lpatiny 
 * @param {number} [options.nbPeaks] Is this value fill it manually and by default it is 1?
 * @param {number} [options.targetX]  what this mean?
 * @param {string} [options.reference]  what this mean?

**Comment by lpatiny** [comment]
From the dialog box we need to specify the from, to.
After we have the choice. Either we use a predefined list of preferences a list could be displayed. This is the 'reference' parameter or we specify the parameters ourself:
- nbPeaks = Number of peaks we need to consider to setup the preference
- reference = The new X value that should be used (need to shift the spectrum so that the middle of all the peaks reach this reference)
-
