### ISSUE TITLE
ACS export and impurtities

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#759]
From ranges when exporting to the string format,

![image](https://user-images.githubusercontent.com/1484241/102104953-131d3b80-3e2f-11eb-90b7-712cc90898c0.png)

Lines tagged as Impurity or Solvent should be filtered out and not appear in this line.

**Comment by hamed-musallam** [comment]
@michaelwenk 
Why you save mixed value if the kind not signal? I need the true change value and not "mixed". so I think you have to create a new key for your purpose without not make your change on the existing key.

What do you think is better for me and you?

**Comment by hamed-musallam** [comment]
@michaelwenk 
What are going to do with this variable?

**Comment by lpatiny** [comment]
@hamed-musallam Please add a link to the code in question

**Comment by michaelwenk** [comment]
@hamed-musallam This "signal" and "mixed" kinds are on ranges/zones level only, not for the signal itself. Since a range could, by theory, contain more than just one "signal" or/and "solvent" or/and "impurity" kinds, I decided for that "mixed" value instead of storing as one value of all them only. Only, if a range/zone contains signals with "signal" kind only, we store it as "signal" range/zone kind. The actual kind of a signal you can still access via the kind on signal level in each range/zone.

**Comment by lpatiny** [comment]
I think that at the level of ranges / zones we should not have the mixed value but keep it empty if it is defined at the level of the signal.
@michaelwenk Why did you add this "mixed" status rather than keeping it empty ?

**Comment by michaelwenk** [comment]
@lpatiny That would be possible to completely delete the kind property on range/zone level, if a range/zone contains non-signals. One could also change property to a boolean value, true for being without non-signals and 0 if non-signal kinds exist in a range/zone.

For now this range/zone kind is used to quickly check whether, e.g. a hint line in 2D chart or a zone rectangle frame color, should be shown or not. So instead of checking each signal separately evening time that value gives immediately the state on range/zone level.
