### ISSUE TITLE
cloning seems useless

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-displayer#813]
Immer should take care of this and duplicating all the data consumes a lot of memory

https://github.com/cheminfo/nmr-displayer/blob/bbf583021cf5915eddc38894885a6f4c8498ced5/src/data/Analysis.js#L240-L241

**Comment by hamed-musallam** [comment]
@lpatiny 
I used the cloning because of immer js because immer js under the hood use Object.freeze and If take a look in Datum1d and datum2d you will find that I'm frequently use cloning and specifically deep clone because of deep objects, Can you asked Michael if he has any idea how to overcome this problem.

**Comment by lpatiny** [comment]
@targos Could you advice on this. Deep cloning does not seem like a good idea.

**Comment by targos** [comment]
If you don't want immer to deeply freeze your object, you can call `Object.freeze()` on it yourself.

**Comment by hamed-musallam** [comment]
@lpatiny @targos 
The problem is after you make the object immutable we need to change the object and or add something to array What to do in this case most of the time we change the datum object for example when we add Peak, integral ... etc

**Comment by targos** [comment]
you can do a shallow clone (only `state.data = Object.freeze({... })`) instead of a deep clone.

**Comment by hamed-musallam** [comment]
@targos 
So first I need to stop deep freeze from immer and use  Object.freeze but the effect of this step on performance, I mean when removing deep freeze for example on datum1d>peaks>{options:{sum:0}, values:[{peak1,2,3 .... stc}]}
actually, we have a deep hierarchical objects tree as I mentioned for the peaks example and the same for integrals ...etc

**Comment by hamed-musallam** [comment]
@targos 
What did is remove cloning and once I load the data I get spectra data and pass to state, the state and Analysis objects are separated, Why Analysis object mutable?

https://github.com/cheminfo/nmr-displayer/blob/9f3476492387052340138ff506e774363a51e16e/src/component/reducer/actions/LoadActions.js#L16-L43

and I even use shallowly Frees 
  const spectraData = Object.freeze(AnalysisObj.getSpectraData());
  const molecules = Object.freeze(AnalysisObj.getMolecules());
  const preferences = Object.freeze(AnalysisObj.getPreferences('1d'));
  const correlations = Object.freeze(AnalysisObj.getCorrelations());
  const spectraAanalysis = Object.freeze(AnalysisObj.getMultipleAnalysis());

it's work if you add peaks but after that, if you try to add integrals or range ... etc, it gives an error because of immutability

**Comment by hamed-musallam** [comment]
@targos 
Can you give your help on this point??

**Comment by targos** [comment]
I'm looking into it now

**Comment by targos** [comment]
I just tried to replace `lodash.cloneDeep` with `Object.freeze` and it seems to work:

![image](https://user-images.githubusercontent.com/2352663/105472536-58d5eb00-5c9c-11eb-9aca-7882de50acc1.png)

**Comment by targos** [comment]
Okay I found a case where that's an issue. Looking further...

**Comment by hamed-musallam** [comment]
@targos 
I get the same error even when I include AnalysisObj inside the state, So I will keep everything as it is and make shallow cloning as you did and prevent autoFreezing by immer js. 

is it ok???

**Comment by hamed-musallam** [comment]
@targos 
the performance becomes bad if I stop automatic freeze for deep objects by immer...
